### ISSUE TITLE
Seyern fails to start

### ISSUE THREAD

**Issue by ichekrygin** [usmanismail/docker-seyren#11]
```
    SEVERE: Exception sending context initialized event to listener instance of class org.jboss.resteasy.plugins.spring.SpringContextLoaderListener
    org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'subscriptionsBean' defined in URL [jar:file:/.extract/webapps/ROOT/WEB-INF/lib/seyren-api-1.2.1.jar!/com/seyren/api/bean/SubscriptionsBean.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.seyren.core.store.ChecksStore]: : Error creating bean with name 'mongoStore' defined in URL [jar:file:/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.2.1.jar!/com/seyren/mongo/MongoStore.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoStore' defined in URL [jar:file:/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.2.1.jar!/com/seyren/mongo/MongoStore.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
            at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:746)
            at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:193)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1075)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:979)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
            at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
            at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
            at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
            at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628)
            at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
            at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
            at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
            at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
            at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
            at org.jboss.resteasy.plugins.spring.SpringContextLoaderListener.contextInitialized(SpringContextLoaderListener.java:44)
            at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797)
            at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5291)
            at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
            at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
            at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoStore' defined in URL [jar:file:/.extract/webapps/ROOT/WEB-INF/lib/seyren-mongo-1.2.1.jar!/com/seyren/mongo/MongoStore.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
            at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1075)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:979)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
            at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
            at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
            at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
            at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:912)
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:855)
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:770)
            at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:811)
            at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:739)
            ... 25 more
    Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.seyren.mongo.MongoStore]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
            at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
            at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
            at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:277)
            ... 38 more
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
            at com.seyren.mongo.MongoStore.<init>(MongoStore.java:74)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
            at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
            ... 40 more
    Caused by: java.lang.RuntimeException: Failed to bootstrap Mongo indexes. Please refer to the logs for more information.
            at com.seyren.mongo.MongoStore.bootstrapMongo(MongoStore.java:88)
            at com.seyren.mongo.MongoStore.<init>(MongoStore.java:72)
            ... 45 more
    Caused by: com.mongodb.CommandFailureException: { "serverUsed" : "172.17.0.9:27017" , "nIndexesWas" : 3 , "ok" : 0.0 , "errmsg" : "index not found with name [checkId_1_target_1]" , "code" : 27}
            at com.mongodb.CommandResult.getException(CommandResult.java:76)
            at com.mongodb.CommandResult.throwOnError(CommandResult.java:131)
            at com.mongodb.DBCollection.dropIndexes(DBCollection.java:1005)
            at com.mongodb.DBCollection.dropIndex(DBCollection.java:1724)
            at com.seyren.mongo.MongoStore.removeOldIndices(MongoStore.java:104)
            at com.seyren.mongo.MongoStore.bootstrapMongo(MongoStore.java:82)
            ... 46 more

    May 10, 2016 9:33:10 PM org.apache.catalina.core.StandardContext startInternal
    SEVERE: Error listenerStart
    May 10, 2016 9:33:11 PM org.apache.catalina.core.StandardContext startInternal
    SEVERE: Context [] startup failed due to previous errors
    May 10, 2016 9:33:11 PM org.apache.catalina.core.ApplicationContext log
    INFO: Closing Spring root WebApplicationContext
    May 10, 2016 9:33:11 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
    SEVERE: The web application [] appears to have started a thread named [cluster-1-172.17.0.9:27017] but has failed to stop it. This is very likely to create a memory leak.
    May 10, 2016 9:33:11 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
    SEVERE: The web application [] appears to have started a thread named [MongoCleaner414130353] but has failed to stop it. This is very likely to create a memory leak.
    May 10, 2016 9:33:11 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
    SEVERE: The web application [] created a ThreadLocal with key of type 
```

**Comment by stefancrain** [comment]
Having the same issue, 
Starting with 

```
docker run -d --name mongodb mongo
docker run -d -p 82:8080 --name seyren --link mongodb:mongodb -e GRAPHITE_URL=http://url:port -it usman/docker-seyren
```

```
$ docker --version
Docker version 1.11.1, build 5604cbe
```

```
$ uname -a
Linux xxxxxyyyzzzz.com 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stefancrain** [comment]
Switching to 

```
docker run -d --name mongodb mongo:3.0.1
```

resolved this issue for me. @ichekrygin give it a try!
